version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cts_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  celery:
    build: ./backend
    container_name: cts_celery
    command: celery -A sorteo worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend

  redis:
    image: redis:7
    container_name: cts_redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: cts_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
