# Generated by Django 4.2.24 on 2025-09-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_won', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de sorteo')),
                ('notified', models.BooleanField(default=False, verbose_name='Notificado')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de notificación')),
                ('valentin_version', models.CharField(default='San Valentín 2025', max_length=50, verbose_name='Edición del sorteo')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='participants.participant', verbose_name='Participante ganador')),
            ],
            options={
                'verbose_name': 'Ganador',
                'verbose_name_plural': 'Ganadores',
                'db_table': 'winners',
                'ordering': ['-date_won'],
                'unique_together': {('participant', 'valentin_version')},
            },
        ),
    ]
